<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=9" />

<script src="jquery.js"></script>
<link href="./bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
<script src="./bootstrap/js/bootstrap.min.js"></script>

<style>
* {
font-family: "Comic Sans MS", Serif;
}

.jumbotron{
  background-image:url('back.jpg');
  background-size:cover;
  color: #FFF;
  text-shadow: 2px 2px #333;
}
</style>

<title>MICoin</title>
</head>
<body>

<?php include("../topbar.php"); ?>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>MICoin</h1>
        <p>THE MOST INTERESTING COIN IN THE WORLD</p>
		        <p><a class="btn btn-primary btn-lg" role="button" href="https://nxtforum.org/assets-board/(ann)(micoin)the-most-interesting-coin-in-the-world-pure-90-pom/">To The MemeChain &raquo;</a></p>

      </div>
    </div>
<div class="container">
	<div class="row"><div class="form-group col-md-12">
			<div class="panel panel-primary">
			<div class="panel-heading"><h3><div class="glyphicon glyphicon-flag"></div> About</h3></div>
			<div class="panel-body">
				<div class="alert alert-warning"><strong>Trolls accepted !</strong></div>
		<div class="row"><div class="col-md-5">
			<img class="img-thumbnail img-responsive" src="./mic.jpg"/>
			</div>
			<div class="col-md-7">
<div class="bs-callout bs-callout-info">
First Proof of Meme Coin [PoM], very creative!<br/>
Number of Coins : 1,000,000,000 MIC<br/>
Genesis Account: NXT-AKCT-VSCJ-C5BC-7YT8S<br/>
Asset Id:  4469670021276890463<br/>
Name of Asset : MIC<br/>
Exchange : AE of Nxt<br/>
</div>
<div class="bs-callout bs-callout-danger">
THE RULES OF DISTRIBUTION OF MIC CHANGE !!! <br/>

From now, there is a thematic for the memes.<br/>

Precisions on the rules :<br/>
<ol>
<li> Any one can change the thematic, but they need to post it in BIG RED TEXT and add a meme as an example.</li>

<li> Only one meme will be credited when 2+ are included in the same post.</li>

<li> Back-to-back posts by the same person will only be paid for once.  The last POMer must wait for someone else to post a meme before they can post a meme for credit.</li>

<li> The memechain only accepts memes generated by the poster.  Take a picture (can be a base meme) and add words, a graphic, SOMETHING RELEVANT TO THE THEMATIC.  Memechain doesn't accept memes generated for another forum/website/etc.  NO MERGE LOLING. </li>
</ol>
</div>

<strong>MUCH LOLING, MUCH MIC !!!</strong>
</div></div>
</div></div></div>
		<div class="form-group col-md-12">
			<div class="panel panel-primary">
			<div class="panel-heading"><h3><div class="glyphicon glyphicon-globe"></div> FAQ</h3></div>
			<div class="panel-body">
<dl class="">

<dt>Is it a fair Coin ?</dt>
<dd>Yes, it is !</dd>
<hr/>
<dt> Is it a Scam ?</dt>
<dd>Post a meme and you will see.</dd>
<hr/>
<dt> How do I get a Stake ?</dt>
<dd>Easy, just post 1 meme of your own creation with your Nxt account ID (NXT-XXXX-XXXX-XXXX-XXXX) in the thread below. For each thematic, one Stake per account and meme. This will be strictly enforced.
Don't use your numeric ID.</dd>
<hr/>
<dt> Is the distribution transparent?</dt>
<dd>Yes, check the Nxt blockchain if you are interested in following the distribution.</dd>
<hr/>
<dt> I don't like "Interesting Men". Your meme sucks!</dt>
<dd>No problem, I like Doges, Kittens and other stuff.</dd>
<hr/>
<dt> I posted my meme from a while ago and I don't have my stake of MIC. You're a scammer.</dt>
<dd>I have an interesting real life. Be patient with one of the most interesting men in the world!</dd>
<hr/>
<dt> Is it a DOGE clone ? </dt>
<dd>No, but DOGE is the second most interesting coin in the world.</dd>

<hr/>

<dt> Are you BCNext ? </dt>
<dd>Yes, I am. I give my Creation to the world and then I don't care. If you want to promote MICoin, you can do it without me.</dd>
<hr/>
<dt> I have a lot of sockpuppet accounts. Can I use it!</dt>
<dd>If it's an interesting sockpuppet, yes.</dd>
<hr/>
<dt> Why is the coin on the top of Nxt ?</dt>
<dd>It is groundbreaking. It is fast, slick and Nxt takes care of securing the coin against attack. Much cheap, much ecological.
The truth is that I don't have the skills to create something new.</dd>
<hr/>
<dt> Your coin is very interesting. Can I post "Interested" on the topic ?</dt>
<dd>Yes, you can.</dd>
<hr/>
<dt> I have a lot of interesting questions. Can I ask them here?</dt>
<dd>Yes, but if I don't answer, it's because I have interesting activities to do.</dd>
		
</div></div></div>
		</div>
		
		<div class="row"><div class="form-group col-md-12">
			<div class="panel panel-primary">
			<div class="panel-heading"><h3><div class="glyphicon glyphicon-thumbs-up"></div> How To</h3></div>
			<div class="panel-body">
	<div class="row">
	<div class="col-md-7">
<ol>
<li> Make a Nxt account: <a href="http://nxt.org/">nxt.org</a> </li>
<li> Create the most interesting meme in the world: <a href="http://www.livememe.com"> livememe.org</a> </li>
<li> Click on the reply button.</li>
<li> Post your Nxt ID and your meme.</li>
</ol>
<div class="alert alert-info">
If you need free NXT for the transactions fees: <a href="http://freenxt.org/">freenxt.org</a> or<br/>
<strong>Much EASY !!!</strong>
</div>

<div class="bs-callout bs-callout-warning">
Sell on the Asset Exchange of Nxt.<br/>
0.0001 NXT * 110,000,000 MIC = 11'000 NXT<br/>
Cost of the Coin: 1000 NXT to create the Asset + 10000 transfers * 1 NXT (it's fees) = 11000 NXT<br/>
---------<br/>
Distribution PoM : 890,000,000 MIC<br/>
10'000 stake of 89000 MIC
</div>
</div>
<div class="col-md-5">
<img class="img-thumbnail img-responsive" src="cat.jpg"/>
</div></div>
		</div></div></div>
		
	</div>
      <hr>

      <footer>
        <p>&copy; NXT Community 2014</p>
      </footer>
    </div> <!-- /container -->
</body>
</html>
